name: Python Setup

on: push

jobs:
    Python-setup:
     runs-on: ubuntu-latest
     steps:
        - name: Python setup
          uses: actions/setup-python@v4
          with:
             python-version: '3.9'
        - name: install dependencies
          run: |
            pip upgrade
            pip install pytest flake8
            