name: Python Setup

on: push

jobs:
    Python-setup:
     runs-on: ubuntu-latest
     steps:
        - name: Python setup
          uses: actions/setup-python@v4
          with:
             python-version: '3.9'
        - name: install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pytest flake8
        - name: Python Installation verification
          run: |
            python3 --version
        - name: Pytest Installation verification
          run: |
            pytest --version
        - name: Flake8 Installation verification
          run: |
            flake8 --version

